language: node_js
node_js:
  - 0.12

before_install:
  - npm install -g typescript typings

install:
  - npm install
  - typings install --global --save dt~react
  - typings install --global --save dt~react-dom

script:
  - npm run build

notifications:
  email: false
